name = "Wanderlust Create"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b71a6a20dde2c00179d07c3e2a0acee7a43a79273246a20edfea838ddc837616"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
