name = "Wanderlust Create"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd485426afd21d6242348197a213fdc676ed24e83ba8e28360ad6cff2c3c3f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
