name = "Wanderlust Create"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b277c5aa62062edd877c09cfa369122d12938f8d4076bd13e6bc677ea8089a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
