name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dbd8e4e436ddfef0e56f128c25a0754789b195274e7a9168e9b5a712047a0ab"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
