name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e56bccd82820cd49f697e773c578e784a35157c660d1207c708b0a2f8e73d0d"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
