name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c30dcacad184beaea89ebf94ffa33c0f5fd759fcc3cf8380c174ba9063d727"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
