name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d0077c79ebf733b6ba9507d5d0cdeab3e6c252e95f4adbdb0c580ccf3c4ea2"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
