name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186c8df02eb38dd3a6022760182606e1f97305cffc54904e38c49efd8877eefb"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
