name = "Wanderlust Stray Souls"
author = "furigin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4107f5aaf3eae0382fb746cc4daec83df2844763511daae5cf6af3d1818fa0b8"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.75"
